# Generated by Django 2.1.1 on 2019-06-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Модель')),
                ('cost', models.CharField(max_length=50, verbose_name='Стоимость')),
                ('op_s', models.CharField(choices=[('android', 'android'), ('windows', 'windows'), ('ios', 'ios')], max_length=50)),
            ],
        ),
    ]
