# Generated by Django 2.1.5 on 2019-06-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_auto_20190611_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='op_s',
            field=models.CharField(choices=[('android', 'android'), ('ios', 'ios'), ('windows', 'windows')], max_length=50),
        ),
    ]
