# Generated by Django 2.1.5 on 2019-06-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0005_auto_20190611_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='fm_radio',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='op_s',
            field=models.CharField(choices=[('android', 'android'), ('windows', 'windows'), ('ios', 'ios')], max_length=50),
        ),
    ]
