# Generated by Django 2.1.1 on 2019-06-20 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0007_auto_20190612_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='prod',
        ),
        migrations.RemoveField(
            model_name='prod',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='prod',
            name='feature_one',
        ),
        migrations.RemoveField(
            model_name='prod',
            name='feature_two',
        ),
        migrations.RemoveField(
            model_name='prod',
            name='fm_radio',
        ),
        migrations.AddField(
            model_name='phone',
            name='brand',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='prod',
            name='feature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='phones.Phone'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='op_s',
            field=models.CharField(choices=[('ios', 'ios'), ('android', 'android'), ('windows', 'windows')], max_length=50),
        ),
    ]
