# Generated by Django 2.1.1 on 2019-06-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0008_auto_20190620_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='phone',
            name='op_s',
            field=models.CharField(choices=[('windows', 'windows'), ('android', 'android'), ('ios', 'ios')], max_length=50),
        ),
    ]
