# Generated by Django 2.1.1 on 2019-06-20 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0009_auto_20190620_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prod',
            name='name',
        ),
        migrations.AddField(
            model_name='prod',
            name='phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='phones.Phone'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='op_s',
            field=models.CharField(choices=[('android', 'android'), ('ios', 'ios'), ('windows', 'windows')], max_length=50),
        ),
        migrations.AlterField(
            model_name='prod',
            name='feature',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
