# Generated by Django 2.1.1 on 2019-06-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0011_auto_20190620_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='cam2',
            field=models.BooleanField(default=False),
        ),
    ]
